# Generated by Django 3.0.8 on 2020-07-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comelona', '0003_platillo_brev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platillo',
            name='Brev',
            field=models.TextField(default='Ingredientes', max_length=100),
        ),
    ]
