# Generated by Django 3.0.8 on 2020-08-13 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comelona', '0007_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
