# Generated by Django 3.0.8 on 2020-08-13 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comelona', '0010_auto_20200813_0023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='total',
            new_name='Cantidad',
        ),
    ]
